# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# assuming
# brew install ghostscript imagemagick xpdf
gem "grim"

gem "nokogiri"
